% fit_mdlag_circulant_freq.m
%
% Description: This script fits mDLAG models via frequency domain 
%              approximation to circulant data.
%
% Author: 
%     Evren Gokcen    egokcen@cmu.edu

%% Set up script parameters

set_consts_mdlag_circulant;

%% Fit mDLAG model

% Load synthetic data and ground truth
currDataFile = sprintf('%s/%s', dataDir, dataFile);
ws = load(currDataFile);

% Initialize model
initParams = init_mdlag(ws.seqTrue, ...
                        yDims, ...
                        xDim_fit, ...
                        binWidth,...
                        'covType', covType, ...
                        'prior', prior, ...
                        'randomSeed', randomSeed, ...
                        'saveCcov', saveCcov);

% As a preprocessing step, compute the FFT of the observed data
ws.seqTrue = fftseq(ws.seqTrue, 'y', 'yfft');

% Fit model
[estParams,~,trackedParams,flags] ...
    = em_mdlag_freq(initParams, ...
                    ws.seqTrue, ...
                    xDim_fit, ...
                    'prior', prior, ...
                    'tol', tol, ...
                    'maxIters', maxIters, ...
                    'freqLB', freqLB, ...
                    'freqParam', freqParam, ...
                    'learnDelays', learnDelays, ...
                    'verbose', verbose, ...
                    'minVarFrac', minVarFrac, ...
                    'maxDelayFrac', maxDelayFrac, ...
                    'maxTauFrac', maxTauFrac, ...
                    'pruneX', pruneX, ...
                    'saveXcov', saveXcov, ...
                    'saveCcov', saveCcov);

% Save results 
currSaveDir = sprintf('%s', resultDir);
if isfolder(currSaveDir)
    fprintf('Using existing directory %s...\n', currSaveDir);
else
    fprintf('Making directory %s...\n', currSaveDir);
    mkdir(currSaveDir);
end
currSaveFile = sprintf('%s/mdlag_results_circulant_freq.mat', currSaveDir);
save(currSaveFile, 'estParams', 'trackedParams', 'flags');
      