% runtime_summary.m
%
% Description: Compare runtime performance across mDLAG-time,
%              mDLAG-inducing, and mDLAG-frequency
%
% Author:
%     Evren Gokcen    egokcen@cmu.edu

%% Choose which mDLAG-inducing results to display

NUM_INDUCE = 20;  % 20 for Fig. 5; 32 for Supp. Fig. 4

%% mDLAG-time vs mDLAG-frequency and mDLAG-inducing

load('./results/runtime_mdlag_time.mat');
load('./results/runtime_mdlag_freq.mat');
load(sprintf('./results/runtime_smdlag_S%02d.mat', NUM_INDUCE));

figure;

% Runtime per iteration
lim = 8;
subplot(1,3,1);
hold on;
line([0 lim], [0 lim], 'color', 'k', 'linestyle', '--');
plot(runtime_time.itertimes(:), runtime_sparse.itertimes(:), ...
     'linestyle', 'none', ...
     'color', SPARSECOLOR, ...
     'marker', '.', ...
     'markersize', 10);
plot(runtime_time.itertimes(:), runtime_freq.itertimes(:), ...
     'linestyle', 'none', ...
     'color', FREQCOLOR, ...
     'marker', '.', ...
     'markersize', 10);
plot(median(runtime_time.itertimes(:)), median(runtime_sparse.itertimes(:)), ...
     'linestyle', 'none', ...
     'color', SPARSECOLOR, ...
     'marker', 'o', ...
     'markersize', 5);
plot(median(runtime_time.itertimes(:)), median(runtime_freq.itertimes(:)), ...
     'linestyle', 'none', ...
     'color', FREQCOLOR, ...
     'marker', 'o', ...
     'markersize', 5);
xlim([0 lim]);
ylim([0 lim]);
axis square;
xlabel('Clock time per iteration, mDLAG-time (s)');
ylabel('Clock time per iteration, other (s)');

% Number of iterations
lim = 60000;
subplot(1,3,2);
hold on;
line([10^3 lim], [10^3 lim], 'color', 'k', 'linestyle', '--');
plot(runtime_time.numiters(:), runtime_sparse.numiters(:), ...
     'linestyle', 'none', ...
     'color', SPARSECOLOR, ...
     'marker', '.', ...
     'markersize', 10);
plot(runtime_time.numiters(:), runtime_freq.numiters(:), ...
     'linestyle', 'none', ...
     'color', FREQCOLOR, ...
     'marker', '.', ...
     'markersize', 10);
plot(median(runtime_time.numiters(:)), median(runtime_sparse.numiters(:)), ...
     'linestyle', 'none', ...
     'color', SPARSECOLOR, ...
     'marker', 'o', ...
     'markersize', 5);
plot(median(runtime_time.numiters(:)), median(runtime_freq.numiters(:)), ...
     'linestyle', 'none', ...
     'color', FREQCOLOR, ...
     'marker', 'o', ...
     'markersize', 5);
xlim([10^3 lim]);
ylim([10^3 lim]);
axis square;
xlabel('No. iterations, mDLAG-time');
ylabel('No. iterations, other');
xscale('log');
yscale('log');

% Total runtime
lim = 100;
subplot(1,3,3);
hold on;
line([0.7 lim], [0.7 lim], 'color', 'k', 'linestyle', '--');
plot(runtime_time.runtimes(:)./3600, runtime_sparse.runtimes(:)./3600, ...
     'linestyle', 'none', ...
     'color', SPARSECOLOR, ...
     'marker', '.', ...
     'markersize', 10);
plot(runtime_time.runtimes(:)./3600, runtime_freq.runtimes(:)./3600, ...
     'linestyle', 'none', ...
     'color', FREQCOLOR, ...
     'marker', '.', ...
     'markersize', 10);
plot(median(runtime_time.runtimes(:))./3600, median(runtime_sparse.runtimes(:))./3600, ...
     'linestyle', 'none', ...
     'color', SPARSECOLOR, ...
     'marker', 'o', ...
     'markersize', 5);
plot(median(runtime_time.runtimes(:))./3600, median(runtime_freq.runtimes(:))./3600, ...
     'linestyle', 'none', ...
     'color', FREQCOLOR, ...
     'marker', 'o', ...
     'markersize', 5);
xlim([0.7 lim]);
ylim([0.7 lim]);
axis square;
xlabel('Total clock time, mDLAG-time (hrs)');
ylabel('Total clock time, other (hrs)');
xscale('log');
yscale('log');
