% fit_smdlag_basic_demo.m
%
% Description: Fits mDLAG models via inducing variables (smDLAG) to basic
%              demo data.
%
% Author: 
%     Evren Gokcen    egokcen@cmu.edu

%% Set up script parameters

set_consts_smdlag_basic_demo;

%% Fit smDLAG model

% Load synthetic data and ground truth
currDataFile = sprintf('%s/%s', dataDir, dataFile);
ws = load(currDataFile);

% Initialize model
initParams = init_smdlag(ws.seqTrue, ...
                         yDims, ...
                         xDim_fit, ...
                         binWidth,...
                         'S', S, ...
                         'prior', prior, ...
                         'randomSeed', randomSeed, ...
                         'saveCcov', saveCcov);

% Fit model
[estParams,~,trackedParams,flags] ...
    = em_smdlag(initParams, ...
                ws.seqTrue, ...
                xDim_fit, ...
                'prior', prior, ...
                'tol', tol, ...
                'maxIters', maxIters, ...
                'freqLB', freqLB, ...
                'freqParam', freqParam, ...
                'learnTau', learnTau, ...
                'learnDelays', learnDelays, ...
                'learnInducingLocs', learnInducingLocs, ...
                'verbose', verbose, ...
                'minVarFrac', minVarFrac, ...
                'maxDelayFrac', maxDelayFrac, ...
                'maxTauFrac', maxTauFrac, ...
                'pruneX', pruneX, ...
                'saveCcov', saveCcov, ...
                'saveWcov', saveWcov);

% Save results 
currSaveDir = sprintf('%s', resultDir);
if isfolder(currSaveDir)
    fprintf('Using existing directory %s...\n', currSaveDir);
else
    fprintf('Making directory %s...\n', currSaveDir);
    mkdir(currSaveDir);
end
currSaveFile = sprintf('%s/smdlag_S%03d_results_basic_demo.mat', currSaveDir, S);
save(currSaveFile, 'estParams', 'trackedParams', 'flags');
